name: dwatson-pharmacy-dashboard
services:
  - name: web
    image: koyeb/node:18
    type: web
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8080"
      - name: MONGODB_URI
        secret: mongodb-uri
      - name: JWT_SECRET
        secret: jwt-secret
      - name: ADMIN_PASSWORD
        secret: admin-password
    build:
      type: dockerfile
      dockerfile: |
        FROM node:18-alpine
        WORKDIR /app
        COPY package*.json ./
        RUN npm ci --only=production
        COPY . .
        EXPOSE 8080
        CMD ["npm", "start"]
    healthcheck:
      path: /health
      port: 8080
      interval: 30s
      timeout: 10s
      retries: 3
    regions:
      - fra
      - sin
    scaling:
      min: 1
      max: 3
